apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: pod-cpu-mutator-webhook
webhooks:
- name: pod-cpu-mutator.default.svc
  clientConfig:
    service:
      name: pod-cpu-mutator-service
      namespace: default
      path: /mutate
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURVekNDQWp1Z0F3SUJBZ0lVSjh5cVBUemFKdXNqZjNGZlY4V1lWSEU1T0kwd0RRWUpLb1pJaHZjTkFRRUwKQlFBd09URUxNQWtHQTFVRUJoTUNWVk14Q3pBSkJnTlZCQWdNQWtOQk1RNHdEQVlEVlFRS0RBVk5lVTl5WnpFTgpNQXNHQTFVRUF3d0VUWGxEUVRBZUZ3MHlOVEEzTWprd05USTVNRGxhRncwek5UQTNNamN3TlRJNU1EbGFNRGt4CkN6QUpCZ05WQkFZVEFsVlRNUXN3Q1FZRFZRUUlEQUpEUVRFT01Bd0dBMVVFQ2d3RlRYbFBjbWN4RFRBTEJnTlYKQkFNTUJFMTVRMEV3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQ3VuMTFTU3NybgpZV1k5eTlnV0xCajdqVWtYY0Q5YmhqN3lCN000WFdrWVprRlRXK0NQTURSSmluanBERE1GbUlvVEJpd3p2SmNXCm9ML3dKSEpLck1KRWtlMDB0c3FPdzg0ZThaZVVQb0Z1RjBEZHN2alNBSjdIQ3gzNXE1dWY4Q1Y1dmZBK2JOWnQKNFBIY0VoL0JPNkNPR1MvTG04cXdVVVJZVG14WGVSMXMwbFRuUHRWQVNUcXRrTHZEdWQyMUVuT1IrbmU5bkFTcgpCN2N0MXh6akpUclpnckJtdENpeFc1S3lReFZRZlg1Z1ZDTDRrbFlWVUFTY1Vnb3RLT0NqZmxPdUZEZ1I4MGFaClljcXJRVCtqN0JOSkJ4TFVGOUs3SHBvdnpkblVzVVdYYmVGc0kwcnlXTi92aUE0bE1EZjI0TFQyaHpWYjdCazAKbG9WdkJSR0tpN29uQWdNQkFBR2pVekJSTUIwR0ExVWREZ1FXQkJTY1dXT2lhbERLNStUYU42N295a0o5VlJrRwp5akFmQmdOVkhTTUVHREFXZ0JTY1dXT2lhbERLNStUYU42N295a0o5VlJrR3lqQVBCZ05WSFJNQkFmOEVCVEFECkFRSC9NQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUFML2lCVkI0TGJiZy9Wbm9SaS9KUEk4MHd0eGt1bjN6UFMKVDlQazJETTEybERndHZkYTBZc282VEJyaHF5eWRLQzVFMzRYR1RyV2ZCK00vQTZVMHJ4WXVJU0lCRTNoQUNZSAoxYnI0MWNlOC9jdG5tWGRleGFuWW9kVStVekhWSWs1Vll3aC9Hb3pIci9pbFpKQ2I2NUdxNGs2V1ZNNjFmVC85Cnl3UHpCSW5MeEFZRFdxM0pQcHhrT1VYUnhub1h1ZldxQzZHNm5oa1pEYlA1WXpla20rM1dUenpnSE1oYnE4b0gKODZZM3lKV2VIQ25NVFo4WTQxT0tvaWtVM3ZnZFZGUC93NHU5U3VuSS9uYk5zRVZLSStjM290eERKNTExdTJhVApCOWlTM01FL2VmWEI0QXhXOFpIZTkwQ0xiSzhqY01QYnVrYkZTRzVseEs0WC9EK3UrWGR5Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  rules:
  - operations: ["CREATE"]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
  admissionReviewVersions: ["v1", "v1beta1"]
  sideEffects: None
  failurePolicy: Fail
