apiVersion: v1
kind: Service
metadata:
  name: pod-cpu-mutator-service
  namespace: default
  labels:
    app: pod-cpu-mutator
spec:
  selector:
    app: pod-cpu-mutator
  ports:
  - name: webhook
    port: 443
    targetPort: 8443
    protocol: TCP
  type: ClusterIP
